<?php

namespace ScolariteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnneeUnivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeUnivRepository extends EntityRepository
{
}
